### ISSUE TITLE
Button "clear message" doesn't work

### ISSUE THREAD

**Issue by azdkj532** [NTUOSC/mercurius-union#7]
As title.

**Comment by azdkj532** [comment]
It works fine on laptop, but not on tablet.

**Comment by azdkj532** [comment]
```
TypeError: $$('button').forEach is not a function. (In '$$('button').forEach', '$$('button').forEach' is undefined)
```

**Comment by bobby1030** [comment]
@azdkj532 More details about your environment of tablet?

**Comment by azdkj532** [comment]
@bobby1030 
iOS 9.3 on iPad Air.
iOS 8.1 on iPad Air (Xcode simulator).

**Comment by bobby1030** [comment]
For me, works on Chrome 54 & Firefox 51 on Linux.
Not working on Firefox Beta 51 on Android.

**Comment by azdkj532** [comment]
#9

**Comment by bobby1030** [comment]
Oops...
I misunderstood the issue, I think.

**Comment by azdkj532** [comment]
Never mind, bug fixed.
